# Generated by Django 4.1.7 on 2023-03-12 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='pname',
        ),
    ]
