# Generated by Django 4.1.7 on 2023-03-12 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_checkout_pname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='prod',
            new_name='pname',
        ),
    ]
